### ISSUE TITLE
How do I mark the type of transmitted data stream？

### ISSUE THREAD

**Issue by phf913820** [ceyhunozkaptan/gr-mimo-ofdm-jrc#1]
Hello, I'd like to ask you a question. I am sending a stream of DATA from Socket PDU module, but I don't know how the Stream Encoder module will mark it as NDP or DATA. And I run the sender flowchart and it shows the following error:

![微信图片_20230526132211](https://github.com/ceyhunozkaptan/gr-mimo-ofdm-jrc/assets/103445931/33ef8b88-0e6a-4516-8efa-37cfead14a8a)

Do you know how I can solve this problem？

**Comment by ceyhunozkaptan** [comment]
Hello, 
Can you look at this [Packet Generator App](https://github.com/ceyhunozkaptan/mimo-ofdm-packet-generator)? We implemented this application to generate basic packets for GnuRadio to transmit. We marked the first byte of the packet to distinguish between DATA and NDP. Please take a look at txworker.cpp for details.

**Comment by phf913820** [comment]
Ok, thank you very much. But When I opened the link, it said it couldn't open. Maybe this link is not working. I would really appreciate it if you could resend it.

**Comment by ceyhunozkaptan** [comment]
Can you please try again?

**Comment by phf913820** [comment]
That's fine now. Thanks.

**Comment by phf913820** [comment]
Hello, I have a new problem.I used two antennas as the transmitter and one antenna as the receiver to verify only the communication function. Set related parameters as follows：

_Sample rates: 1MHz
Gain: 50 dB
Center frequency: 5 GHz_

When I send an NDP frame, I can detect frames, but the constellations are messy. The following error message is displayed: DATA Checksum is wrong--Dropping Packet, bytes: 7. 
![1](https://github.com/ceyhunozkaptan/gr-mimo-ofdm-jrc/assets/103445931/8bff9877-9733-4479-aec2-0542c028cdc4)

When I sent the precoded DATA frame, the number of bits dropped was even higher:
![2](https://github.com/ceyhunozkaptan/gr-mimo-ofdm-jrc/assets/103445931/dc86a4e9-eaa4-4c91-9bb1-2f96fc7b967b)

Do you have any idea what the problem might be?
