### ISSUE TITLE
Hello, I have a new problem.I used two antennas as the transmitter and one antenna as the receiver to verify only the communication function. Set related parameters as follows：

### ISSUE THREAD

**Issue by ceyhunozkaptan** [ceyhunozkaptan/gr-mimo-ofdm-jrc#2]
Hello, I have a new problem.I used two antennas as the transmitter and one antenna as the receiver to verify only the communication function. Set related parameters as follows：

_Sample rates: 1MHz
Gain: 50 dB
Center frequency: 5 GHz_

When I send an NDP frame, I can detect frames, but the constellations are messy. The following error message is displayed: DATA Checksum is wrong--Dropping Packet, bytes: 7. 
![1](https://github.com/ceyhunozkaptan/gr-mimo-ofdm-jrc/assets/103445931/8bff9877-9733-4479-aec2-0542c028cdc4)

When I sent the precoded DATA frame, the number of bits dropped was even higher:
![2](https://github.com/ceyhunozkaptan/gr-mimo-ofdm-jrc/assets/103445931/dc86a4e9-eaa4-4c91-9bb1-2f96fc7b967b)

Do you have any idea what the problem might be?

_Originally posted by @phf913820 in https://github.com/ceyhunozkaptan/gr-mimo-ofdm-jrc/issues/1#issuecomment-1605854685_

**Comment by phf913820** [comment]
I changed the gain, sample rate, etc., but the packet drop still happened, and I didn't know why it happened. Can you help me analyze it? Thanks.

**Comment by ceyhunozkaptan** [comment]
> I changed the gain, sample rate, etc., but the packet drop still happened, and I didn't know why it happened. Can you help me analyze it? Thanks.

If the frame detection is happening, it means transmission and reception happens somewhat correctly but demodulation has issues. Possible reasons might be low SNR or very high Carrier Frequency Offset (CFO) which may not be corrected if too high. 

As a first step of debug,  I would suggest testing with a simple loopback setup where TX is connected to RX with a coax cable (may sure to add attenuator and use very low transmit power to protect). Using the same SDR would ensure that the CFO is zero.

**Comment by phf913820** [comment]
Thanks for your answer. Using the same equipment, I found that it was not the CFO's problem. I think it may be related to the signal-to-noise ratio. Now I use two antennas for the transmitter and two antennas for the receiver. When I use BPSK and QPSK modulation, the constellation diagram can be demodulated normally. However, when QAM modulation is adopted and only NDP frames are sent,  the frame detection happens but the constellation diagram corresponding to the two signals is relatively chaotic. The packet error rates of the two signals are about 30% and 100%, respectively. In addition, I’ve attached three screenshots showing my flow diagram. I suspect that it may have something to do with signal-to-noise ratio or synchronization. Could you give me some advice?
![11](https://github.com/ceyhunozkaptan/gr-mimo-ofdm-jrc/assets/103445931/51e2458e-d420-4af7-aa72-84a8a4535c9c)
![2](https://github.com/ceyhunozkaptan/gr-mimo-ofdm-jrc/assets/103445931/4f6f33aa-bb15-48ad-b899-6899f457dff7)

**Comment by ceyhunozkaptan** [comment]
Hi, if the QAM is the only modulation working, then you are limited by the SNR as QAM requires high SNR. I would suggest testing with a loopback setup to debug underlying issues. I could not think of any other way to fix this issue.
